package pl.darenie.dns.model.enums;

public enum ErrorCode {

    FIREBASE_CREATE_USER_ERROR, USER_ALREADY_FRIEND, CANNOT_ADD_BILL, BILL_NOT_FOUND, SETTLEMENT_NOT_EXIST, NOT_AUTHENTICATED, INVALID_USER_DATA, USER_NOT_FOUND
}
